<?php

namespace ContainerZOrATML;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NbZ3tH7Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NbZ3tH7' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NbZ3tH7'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'postRep' => ['privates', 'App\\Repository\\PostRepository', 'getPostRepositoryService', true],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', true],
        ], [
            'postRep' => 'App\\Repository\\PostRepository',
            'serializer' => '?',
        ]);
    }
}
