<?php

namespace ContainerZOrATML;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_I6bABjAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.i6bABjA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.i6bABjA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'post' => ['privates', '.errored..service_locator.i6bABjA.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.i6bABjA": it references class "App\\Entity\\Post" but no such service exists.'],
        ], [
            'entityManager' => '?',
            'post' => 'App\\Entity\\Post',
        ]);
    }
}
