<?php

namespace ContainerROvlPDg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QfKLpQgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qfKLpQg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qfKLpQg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\PostController::collection' => ['privates', '.service_locator.NbZ3tH7', 'get_ServiceLocator_NbZ3tH7Service', true],
            'App\\Controller\\PostController::delete' => ['privates', '.service_locator.i6bABjA', 'get_ServiceLocator_I6bABjAService', true],
            'App\\Controller\\PostController::item' => ['privates', '.service_locator.LiOQ1Rg', 'get_ServiceLocator_LiOQ1RgService', true],
            'App\\Controller\\PostController::post' => ['privates', '.service_locator.Rqetkge', 'get_ServiceLocator_RqetkgeService', true],
            'App\\Controller\\PostController::put' => ['privates', '.service_locator.JJ3ZC5R', 'get_ServiceLocator_JJ3ZC5RService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel::terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
            'App\\Controller\\PostController:collection' => ['privates', '.service_locator.NbZ3tH7', 'get_ServiceLocator_NbZ3tH7Service', true],
            'App\\Controller\\PostController:delete' => ['privates', '.service_locator.i6bABjA', 'get_ServiceLocator_I6bABjAService', true],
            'App\\Controller\\PostController:item' => ['privates', '.service_locator.LiOQ1Rg', 'get_ServiceLocator_LiOQ1RgService', true],
            'App\\Controller\\PostController:post' => ['privates', '.service_locator.Rqetkge', 'get_ServiceLocator_RqetkgeService', true],
            'App\\Controller\\PostController:put' => ['privates', '.service_locator.JJ3ZC5R', 'get_ServiceLocator_JJ3ZC5RService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.KfbR3DY', 'get_ServiceLocator_KfbR3DYService', true],
            'kernel:terminate' => ['privates', '.service_locator.KfwZsne', 'get_ServiceLocator_KfwZsneService', true],
        ], [
            'App\\Controller\\PostController::collection' => '?',
            'App\\Controller\\PostController::delete' => '?',
            'App\\Controller\\PostController::item' => '?',
            'App\\Controller\\PostController::post' => '?',
            'App\\Controller\\PostController::put' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\PostController:collection' => '?',
            'App\\Controller\\PostController:delete' => '?',
            'App\\Controller\\PostController:item' => '?',
            'App\\Controller\\PostController:post' => '?',
            'App\\Controller\\PostController:put' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
