<?php

namespace ContainerROvlPDg;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_JJ3ZC5RService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.JJ3ZC5R' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.JJ3ZC5R'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', true],
            'post' => ['privates', '.errored..service_locator.JJ3ZC5R.App\\Entity\\Post', NULL, 'Cannot autowire service ".service_locator.JJ3ZC5R": it references class "App\\Entity\\Post" but no such service exists.'],
            'serializer' => ['services', '.container.private.serializer', 'get_Container_Private_SerializerService', false],
        ], [
            'entityManager' => '?',
            'post' => 'App\\Entity\\Post',
            'serializer' => '?',
        ]);
    }
}
