<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUsYFju5\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUsYFju5/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUsYFju5.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUsYFju5\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUsYFju5\App_KernelDevDebugContainer([
    'container.build_hash' => 'UsYFju5',
    'container.build_id' => '9a3771d9',
    'container.build_time' => 1634952459,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUsYFju5');
