<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerGvrkcjT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerGvrkcjT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerGvrkcjT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerGvrkcjT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerGvrkcjT\App_KernelDevDebugContainer([
    'container.build_hash' => 'GvrkcjT',
    'container.build_id' => '69227221',
    'container.build_time' => 1634981667,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerGvrkcjT');
