<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerROvlPDg\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerROvlPDg/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerROvlPDg.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerROvlPDg\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerROvlPDg\App_KernelDevDebugContainer([
    'container.build_hash' => 'ROvlPDg',
    'container.build_id' => 'ade5491d',
    'container.build_time' => 1635184465,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerROvlPDg');
